#
# Python 3 Titus travis.yml config file
#
# YAML Validator:   http://lint.travis-ci.org/
#

language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
  
# command to install dependencies
install:
  - pip install avro-python3
  - pip install ply
  - pip install pyyaml
  - pip install numpy
  - pip install pytz
  - pip install coverage
  
# command to run tests
script:
  - coverage run setup.py test
  - coverage report
  
# Push the results back to codecov
# after_success:
#   - codecov
notifications:
  email: false
